# Site Settings

title: Shelley Wong's Resume
description: My resume, updated August 2019

# Author Info

author: Shelley Wong
email: swong26@mail.csuchico.edu

exclude: [README.md]

theme: jekyll-theme-cayman
